/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pizzaria.view;

import br.com.pizzaria.util.Global;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Jaime
 */
public class MenuManutencao extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuProdução
     */
    public MenuManutencao() {
        initComponents();
        Timer time = new Timer(1000,ativar);
        time.start(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPedidoBalcao = new javax.swing.JButton();
        btnPedidoBalcao1 = new javax.swing.JButton();
        btnPedidoBalcao2 = new javax.swing.JButton();
        btnPedidoBalcao3 = new javax.swing.JButton();
        btnPedidoBalcao4 = new javax.swing.JButton();

        setTitle("Menu Manutenção");

        btnPedidoBalcao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedidoBalcao.setForeground(new java.awt.Color(0, 51, 255));
        btnPedidoBalcao.setText("Funcionário");
        btnPedidoBalcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoBalcaoActionPerformed(evt);
            }
        });

        btnPedidoBalcao1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedidoBalcao1.setForeground(new java.awt.Color(0, 51, 255));
        btnPedidoBalcao1.setText("Entregador");
        btnPedidoBalcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoBalcao1ActionPerformed(evt);
            }
        });

        btnPedidoBalcao2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedidoBalcao2.setForeground(new java.awt.Color(0, 51, 255));
        btnPedidoBalcao2.setText("Usuário");
        btnPedidoBalcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoBalcao2ActionPerformed(evt);
            }
        });

        btnPedidoBalcao3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedidoBalcao3.setForeground(new java.awt.Color(0, 51, 255));
        btnPedidoBalcao3.setText("<html> Função/<br/> Cargo");
        btnPedidoBalcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoBalcao3ActionPerformed(evt);
            }
        });

        btnPedidoBalcao4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedidoBalcao4.setForeground(new java.awt.Color(0, 51, 255));
        btnPedidoBalcao4.setText("Módulo");
        btnPedidoBalcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoBalcao4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPedidoBalcao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedidoBalcao2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPedidoBalcao, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPedidoBalcao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPedidoBalcao3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPedidoBalcao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidoBalcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidoBalcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidoBalcao4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidoBalcao3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidoBalcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoBalcaoActionPerformed
        
    }//GEN-LAST:event_btnPedidoBalcaoActionPerformed

    private void btnPedidoBalcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoBalcao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidoBalcao1ActionPerformed

    private void btnPedidoBalcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoBalcao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidoBalcao2ActionPerformed

    private void btnPedidoBalcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoBalcao3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidoBalcao3ActionPerformed

    private void btnPedidoBalcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoBalcao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidoBalcao4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedidoBalcao;
    private javax.swing.JButton btnPedidoBalcao1;
    private javax.swing.JButton btnPedidoBalcao2;
    private javax.swing.JButton btnPedidoBalcao3;
    private javax.swing.JButton btnPedidoBalcao4;
    // End of variables declaration//GEN-END:variables
    ActionListener ativar = (  
        new ActionListener(){  
            public void actionPerformed(ActionEvent e){  
                centralizarComponente();
            }  
          
        }  
    );
    
    public final void centralizarComponente() {  
       int x = Global.principal.getLocation().x;
       int y = Global.principal.getLocation().y;
        
        Dimension ds = Global.principal.getSize();
        Dimension dw = getSize();  
        setLocation((0), (0));  
    }
}
