/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pizzaria.view;

import br.com.pizzaria.bean.PrecoProdutoBean;
import br.com.pizzaria.controller.PedidoController;
import br.com.pizzaria.model.ProdutoModel;
import br.com.pizzaria.model.TipoProdutoModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import br.com.pizzaria.bean.ProdutoBean;
import br.com.pizzaria.bean.TipoProdutoBean;
import br.com.pizzaria.controller.PrecoProdutoController;
import br.com.pizzaria.controller.ProdutoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import br.com.pizzaria.bean.FornecedorBean;
import br.com.pizzaria.util.ConectaBanco;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author Jaime
 */
public class PedidoCompraView extends javax.swing.JInternalFrame {

    ComboBoxModel<PrecoProdutoBean> modeloComboProd;

    MaskFormatter formatoNascimento;
    ComboBoxModel<TipoProdutoBean> modeloTipoProd;
    ComboBoxModel<TipoProdutoBean> modeloTipoPizza;
    List<TipoProdutoBean> listaTipoProd;
    List<TipoProdutoBean> listaTipoPizza;
    ProdutoController produtoController;
    List<ProdutoBean> listaProduto;
    List<FornecedorBean> listaFornecedor;
    ComboBoxModel<ProdutoBean> modeloPizzaInteira;
    List<ProdutoBean> listaPizzaInteira;
    ComboBoxModel<ProdutoBean> modeloPizzaSabor1;
    List<ProdutoBean> listaPizzaSabor1;
    ComboBoxModel<ProdutoBean> modeloPizzaSabor2;
    List<ProdutoBean> listaPizzaSabor2;
    ComboBoxModel<ProdutoBean> modeloBorda;
    List<ProdutoBean> listaBorda;
    IngredientesPizzaView ingredienteV;
    PedidoController entregaPedidoController;
    PrecoProdutoController precoProdutoController;

    /**
     * Creates new form NotaFiscalEntradaView
     */
    public PedidoCompraView() {

        initComponents();

        precoProdutoController = new PrecoProdutoController();
        produtoController = new ProdutoController();
        modeloTipoProd = cbTipo.getModel();
        populaTipoProduto();
        populaFornecedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtObs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_data2 = new javax.swing.JLabel();
        try{        formatoNascimento = new MaskFormatter("##/##/####");    }catch (Exception Erro){      JOptionPane.showMessageDialog(null, "Data inválida", "ERRO DE FORMATAÇÃO", 0);  }
        txtDtemissao = new JFormattedTextField(formatoNascimento);
        lbl_data6 = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();
        lbl_data7 = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox();
        lblValor3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblValor4 = new javax.swing.JLabel();
        txtValorDes = new javax.swing.JTextField();
        lblValor5 = new javax.swing.JLabel();
        txtValorNf = new javax.swing.JTextField();
        lbl_data10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        lbl_data11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        lbl_data12 = new javax.swing.JLabel();
        txtParc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_data1 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        lbl_data8 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox();
        lbl_data9 = new javax.swing.JLabel();
        txtUM = new javax.swing.JTextField();
        txtproduto = new javax.swing.JTextField();
        lblValor6 = new javax.swing.JLabel();
        lblValor7 = new javax.swing.JLabel();
        txtqtd = new javax.swing.JTextField();
        lblValor8 = new javax.swing.JLabel();
        txtVuni = new javax.swing.JTextField();
        lblValor9 = new javax.swing.JLabel();
        txtVtotal = new javax.swing.JTextField();
        lblValor10 = new javax.swing.JLabel();
        txtVdescon = new javax.swing.JTextField();
        lblValor11 = new javax.swing.JLabel();
        txtVnf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("PEDIDO DE COMPRA");
        setPreferredSize(new java.awt.Dimension(680, 680));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Observação:");

        lbl_data2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data2.setText("Dt. Emissão:");

        txtDtemissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDtemissaoKeyTyped(evt);
            }
        });

        lbl_data6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data6.setText("CNPJ Fornec:");

        txtCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCNPJKeyTyped(evt);
            }
        });

        lbl_data7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data7.setText("Nome Fornecedor:");

        cbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFornecedorActionPerformed(evt);
            }
        });

        lblValor3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor3.setText("Vlr. Total:");

        txtTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTotalFocusLost(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });

        lblValor4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor4.setText("Vlr. Desc:");

        txtValorDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorDesFocusLost(evt);
            }
        });
        txtValorDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorDesKeyTyped(evt);
            }
        });

        lblValor5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor5.setText("Vlr. NF:");

        txtValorNf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorNfFocusLost(evt);
            }
        });
        txtValorNf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorNfKeyTyped(evt);
            }
        });

        lbl_data10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data10.setText("Cond. Pagto.:");

        lbl_data11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data11.setText("Forma Pagto.:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha forma de Pagamento", "Dinheiro", "Cartão de Crédito", "Cartão de Débito" }));

        lbl_data12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data12.setText("Parcelas:");

        txtParc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParcActionPerformed(evt);
            }
        });
        txtParc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParcKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblValor3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(lblValor4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorDes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValor5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorNf, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_data2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDtemissao)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_data10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_data11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_data12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtParc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_data6)
                            .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_data7)))
                    .addComponent(txtObs))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_data6)
                    .addComponent(lbl_data7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_data2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_data10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_data11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_data12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorNf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens"));

        lbl_data1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data1.setText("Tipo Produto:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar Tipo Produto" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        lbl_data8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data8.setText("Produto:");

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar Produto" }));
        cbProduto.setEnabled(false);
        cbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdutoActionPerformed(evt);
            }
        });

        lbl_data9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data9.setText("Unid. Med.");

        txtproduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprodutoFocusLost(evt);
            }
        });
        txtproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprodutoKeyTyped(evt);
            }
        });

        lblValor6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor6.setText("Ref. Produto");

        lblValor7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor7.setText("Qtde:");

        txtqtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtqtdFocusLost(evt);
            }
        });
        txtqtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtqtdKeyTyped(evt);
            }
        });

        lblValor8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor8.setText("Vlr. Unit.:");

        txtVuni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVuniFocusLost(evt);
            }
        });
        txtVuni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVuniKeyTyped(evt);
            }
        });

        lblValor9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor9.setText("Vlr. Total:");

        txtVtotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVtotalFocusLost(evt);
            }
        });
        txtVtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVtotalKeyTyped(evt);
            }
        });

        lblValor10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor10.setText("Vlr. Desc.:");

        txtVdescon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVdesconFocusLost(evt);
            }
        });
        txtVdescon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVdesconKeyTyped(evt);
            }
        });

        lblValor11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValor11.setText("Vlr. NF.:");

        txtVnf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVnfFocusLost(evt);
            }
        });
        txtVnf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVnfKeyTyped(evt);
            }
        });

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Produto", "U.Med.", "Qtde", "Vlr.Unit.", "Vlr.Total", "Vlr.Desc", "Vlr.NF."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.getTableHeader().setReorderingAllowed(false);
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProdutoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_data1)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_data8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_data9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor6)
                            .addComponent(txtproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor7)
                            .addComponent(txtqtd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor8)
                            .addComponent(txtVuni, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor9)
                            .addComponent(txtVtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblValor10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVdescon, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor11)
                            .addComponent(txtVnf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblValor10, txtVtotal, txtVuni});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_data1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_data8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_data9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblValor6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblValor7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtqtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblValor8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblValor9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblValor10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVdescon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblValor11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton3.setText("Excluir");

        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDtemissaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDtemissaoKeyTyped
        String caracteres = "0987654321";

        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDtemissaoKeyTyped

    private void txtCNPJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNPJKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJKeyTyped

    private void txtTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalFocusLost

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        String caracteres = "0987654321,.";

        if (!caracteres.contains(evt.getKeyChar() + "")) {

            evt.consume();

        }
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtValorDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorDesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDesFocusLost

    private void txtValorDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDesKeyTyped

    private void txtValorNfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorNfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorNfFocusLost

    private void txtValorNfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorNfKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorNfKeyTyped

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed

        TipoProdutoModel produt = new TipoProdutoModel();

        if (cbTipo.getSelectedIndex() > 0) {
            //limpaCampos();
            cbProduto.removeAllItems();
            cbProduto.setEnabled(true);
            populaListaProduto();

        } else {
            cbProduto.setEnabled(true);
            cbProduto.setSelectedIndex(0);
            //  limpaCampos();
        }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void cbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdutoActionPerformed

        if (cbProduto.getSelectedIndex() > 0) {

            //      txtTotal.setText(consultaEstoqueController.controleDeValor(((ProdutoBean) cbProduto.getSelectedItem()).getCodigo()) + "");
            //      limpaCampos();
            //cbData.removeAllItems();
            // populaListaData();
            //cbData.setEnabled(true);
            //  txtTotal.setText(decimalFormato.format(((ProdutoBean) cbProduto.getSelectedItem()).getPrecoProduto().getPreco()).replace(",", "."));
        } else {
            //                cbData.setEnabled(false);
            //                  cbData.setSelectedIndex(0);
//                    limpaCampos();
        }
    }//GEN-LAST:event_cbProdutoActionPerformed

    private void txtprodutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprodutoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodutoFocusLost

    private void txtprodutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodutoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodutoKeyTyped

    private void txtqtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtqtdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtdFocusLost

    private void txtqtdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtdKeyTyped

    private void txtVuniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVuniFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVuniFocusLost

    private void txtVuniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVuniKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVuniKeyTyped

    private void txtVtotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVtotalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVtotalFocusLost

    private void txtVtotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVtotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVtotalKeyTyped

    private void txtVdesconFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVdesconFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVdesconFocusLost

    private void txtVdesconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVdesconKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVdesconKeyTyped

    private void txtVnfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVnfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVnfFocusLost

    private void txtVnfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVnfKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVnfKeyTyped

    private void tblProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMousePressed
//        produtoBeans = produtoController.controlePreenchimento(((ProdutoBean) modeloTabela.getValueAt(tblProduto.getSelectedRow(), 0)).getCodigo());
//
//        System.out.println(produtoBeans.getTipoProduto().getDescricao());
//        txaDescricao.setText(produtoBeans.getDescricao());
//        modeloTipoProd.setSelectedItem(produtoBeans.getTipoProduto());
//        txtPreco.setText(String.valueOf(formatoDecimal.format(produtoBeans.getPrecoProduto().getPreco())));
//        if (String.valueOf(produtoBeans.getEstocavel()).equals("S")) {
//            cbEstocavel.setSelectedIndex(0);
//        } else {
//            cbEstocavel.setSelectedIndex(1);
//        }
//        if (String.valueOf(produtoBeans.getAvisaEstoqueMinimo()).equals("S")) {
//            cbAvisa.setSelectedIndex(0);
//        } else {
//            cbAvisa.setSelectedIndex(1);
//        }
//
//        if (produtoBeans.getProdAcabadoPrima() == 'P') {
//            rbMateriaPrima.setSelected(true);
//        } else {
//            rbProdAcabado.setSelected(true);
//        }
//
//        if (produtoBeans.getVenda() == 'S') {
//            cbxProdutoVenda.setSelected(true);
//        } else {
//            cbxProdutoVenda.setSelected(false);
//        }
//
//        txtQtd.setText(String.valueOf(produtoBeans.getQtdMinima()));
//        //txtQtdEstoque.setText(String.valueOf(produtoBeans.getQtdSaldoEstoque()));
//        txtData.setText(produtoBeans.getDataCad());
//
//        modeloUnidade.setSelectedItem(produtoBeans.getUnidadeMedida());
    }//GEN-LAST:event_tblProdutoMousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtParcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParcActionPerformed

    private void txtParcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParcKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParcKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFornecedorActionPerformed

        if (cbFornecedor.getSelectedIndex() >= 0) {

            capituraCnpj();
        }

    }//GEN-LAST:event_cbFornecedorActionPerformed
    public void populaTipoProduto() {
        ProdutoModel produtoModel = new ProdutoModel();

        listaTipoProd = new ArrayList<>();
        produtoModel.populaListaTipoProduto(listaTipoProd);
        for (TipoProdutoBean tipoProdutoBeans : listaTipoProd) {
            cbTipo.addItem(tipoProdutoBeans);
        }
    }

    public void populaListaProduto() {

        ProdutoBean p = new ProdutoBean();
        //JOptionPane.showMessageDialog(null,p.ToString());

        listaProduto = new ArrayList<>();
        precoProdutoController.controleListaProduto(listaProduto, ((TipoProdutoBean) modeloTipoProd.getSelectedItem()).getCodigo());
        for (ProdutoBean prdutoBeans : listaProduto) {
            cbProduto.addItem(prdutoBeans);
        }

    }

    public void populaFornecedor() {

        String SQLSelection = "SELECT\n"
                + "  `for_nome`\n"
                + "  \n"
                + "FROM `pizzaria`.`fornecedor`\n"
                + "WHERE `for_status` ='Ativo' ;";

        try (PreparedStatement pstm = ConectaBanco.getConnection().prepareStatement(SQLSelection)) {

            ResultSet rs = pstm.executeQuery();

            while (rs.next()) {
                FornecedorBean novo = new FornecedorBean();

                novo.setNome(rs.getString("for_nome"));

                cbFornecedor.addItem(novo);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossível Carregar Lista " + ex, "Erro de SQL ", 0, new ImageIcon("imagens/cancelar.png"));
        }

    }

    public void capituraCnpj() {

        String name = cbFornecedor.getSelectedItem().toString();

        String SQLSelection = "SELECT\n"
                + " `for_cod_pfj`,"
                + "FROM `pizzaria`.`fornecedor`\n"
                + "WHERE `for_nome` = wilkor;";

        try (PreparedStatement pstm = ConectaBanco.getConnection().prepareStatement(SQLSelection)) {

            ResultSet rs = pstm.executeQuery();

            txtCNPJ.setText(rs.getString("for_cod_pfj`"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossível Carregar Lista " + ex, "Erro de SQL ", 0, new ImageIcon("imagens/cancelar.png"));
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JComboBox cbProduto;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValor10;
    private javax.swing.JLabel lblValor11;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JLabel lblValor4;
    private javax.swing.JLabel lblValor5;
    private javax.swing.JLabel lblValor6;
    private javax.swing.JLabel lblValor7;
    private javax.swing.JLabel lblValor8;
    private javax.swing.JLabel lblValor9;
    private javax.swing.JLabel lbl_data1;
    private javax.swing.JLabel lbl_data10;
    private javax.swing.JLabel lbl_data11;
    private javax.swing.JLabel lbl_data12;
    private javax.swing.JLabel lbl_data2;
    private javax.swing.JLabel lbl_data6;
    private javax.swing.JLabel lbl_data7;
    private javax.swing.JLabel lbl_data8;
    private javax.swing.JLabel lbl_data9;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtDtemissao;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtParc;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUM;
    private javax.swing.JTextField txtValorDes;
    private javax.swing.JTextField txtValorNf;
    private javax.swing.JTextField txtVdescon;
    private javax.swing.JTextField txtVnf;
    private javax.swing.JTextField txtVtotal;
    private javax.swing.JTextField txtVuni;
    private javax.swing.JTextField txtproduto;
    private javax.swing.JTextField txtqtd;
    // End of variables declaration//GEN-END:variables

}
